protected/models/Archive.php
<?php

/**
 * This is the model class for table "archive".
 *
 * The followings are the available columns in table 'archive':
 * @property integer $id
 * @property integer $is_container
 * @property string $name
 * @property string $path
 * @property string $extension
 * @property integer $author
 * @property string $description
 * @property integer $container
 * @property string $created
 *
 * The followings are the available model relations:
 * @property User $author0
 */
class Archive extends CActiveRecord
{
	
	public $baseDir;
	public $archiveRoot = '/files/archive/';
	public $file;
	public $searchText=Null;

	public function init()
	{
		$this->baseDir = dirname(Yii::app()->request->scriptFile);
	}
	
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Archive the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'archive';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name, path, author, description, created', 'required', 'on'=>'uploadFile'),
			array('name, path, author, description, created', 'required', 'on'=>'createContainer'),
			array('name, description', 'required', 'on'=>'update'),
			array('author, container', 'numerical', 'integerOnly'=>true),
			array('description', 'length', 'max'=>2000),
			array('name, path', 'length', 'max'=>255),
			array('extension', 'length', 'max'=>5),
			// The following rule is used by search().
			array('searchText', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'author0' => array(self::BELONGS_TO, 'User', 'author'),
			'container0' => array(self::BELONGS_TO, 'Archive', 'container'),
		);
	}
	
	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'file' => __('File'),
			'name' => __('Name'),
			'path' => __('Path'),
			'extension' => 'Extension',
			'author' => __('Author'),
			'description' => __('Description'),
			'created' => __('Created'),
			'searchText' => __('Search'),
		);
	}

/*
	protected function beforeSave()
	{
		if (! file_exists($this->getURI()) ){	// let's make sure the file/dir actually exists
			return 0;
		}
		return parent::beforeSave();
	}
*/

	protected function beforeDelete()
	{
		if (file_exists($this->getURI())){
			unlink($this->getURI());
		}
		return parent::beforeDelete();
	}

	public function doesContainerExist()
	{
		if ($this->findAllByAttributes(array('is_container'=>1, 'container'=>$this->container, 'path'=>$this->path))){
			return 1;
		}
		return 0;
	}

	public function getFullname()
	{
		$name = $this->name;
		if ($this->extension){
			$name .= '.'.$this->extension;
		}
		return $name;
	}

	public function getParentContainerName()
	{
		if ($this->container0){
			return $this->container0->name;
		}else{
			return __('index');
		}
	}


	public function getURI()
	{
		if ($this->is_container){
			return Null;
		}
		return $this->baseDir.$this->path;
	}

	public function getURL()
	{
		if ($this->is_container){
			return Yii::app()->createAbsoluteUrl('').$this->getContainerWebPath();
		}
		return Yii::app()->createAbsoluteUrl('').'/archive/'.$this->id;
	}

	public function getParentContainerURL()
	{
		if ($this->container){
			return Yii::app()->createAbsoluteUrl('').$this->container0->getContainerWebPath();
		}else{
			return Yii::app()->createAbsoluteUrl('').'/archive';
		}
	}

	public function getContainerWebPath()
	{
		if (!$this->is_container){
			return '/archive/index';
		}
		$path = ':'.$this->path;
		$model = $this;
		while ($model->container){
			$path = ':'.$model->container0->path.$path;
			$model = $model->container0;
		}
		$path= ltrim ($path, ':');
		return '/archive/d/'.$path;
	}

	public function getParentContainerWebPath()
 	{
		if (!$this->container){
			return 'archive/index';
		}
		return $this->container0->getContainerWebPath();
	}

	public function getContainerFromPath($containerPath)
	{
		$pathComponents = explode(':', $containerPath);
		$container = Null;
		$containerID = Null;
		while($pathComponents){	
			$path = array_shift($pathComponents);
			$container = $this->findByAttributes(array('is_container'=>1, 'path'=>$path, 'container'=>$containerID));
			if (!$container){
				break;
			}
			$containerID = $container->id;
		}
		return $container;
	}

	public function isChildOf($parent)
	{
		$loop = true;
		$model = $this;
		while ($loop){
			if (!$model->container){
				$loop = false;
			}else{
				if($model->container0->id == $parent->id){
					return 1;
				}
				$model = $model->container0;
			}
		}
		return 0;
	}

	public function canEdit($user_id, $is_admin){	
		if ($this->author == $user_id || $is_admin){
			return true;
		}
		return false;
	}

	public function getExtension($file_name){
		return pathinfo($file_name, PATHINFO_EXTENSION);
	}

 	public function setFilePath()
	{
		$path = substr(md5(rand(0, 1000000)), 0, 45);
		while($this->findAllByAttributes(array('path'=>$this->archiveRoot.$path))){
			$path = substr(md5(rand(0, 1000000)), 0, 45);
		}
		$this->path = $this->archiveRoot.$path;
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search($container = Null)
	{
		$criteria=new CDbCriteria;
		$text = $this->searchText;
		
		$criteria->addCondition("name LIKE :match OR description LIKE :match");
		$criteria->params[':match'] = "%$text%";

		if (!$text){
			if ($container){
				$criteria->compare('container', $container->id);
			}else{
				$criteria->addCondition('container is NULL');
			}
		}
		$criteria->order = 'is_container DESC, name ASC';
		
		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
			'pagination'=>array('pageSize'=>20),
		));
	}
	
	/* I want to use a webfont in the <td> element and I don't know how to do it without using the label
	 * This gets called from the CGrid
	 */
	public function getShareColumnItem()
	{
		return '<span style="position:relative"><i class="icon-share" onClick="js:loadSocialWidgets(\''.$this->id.'\', this)"></i></span>';
	} 
}

protected/controllers/NewsletterController.php
<?php
/**
 * OCAX -- Citizen driven Observatory software
 * Copyright (C) 2014 OCAX Contributors. See AUTHORS.

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

class NewsletterController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','feed'),
				'users'=>array('*'),
			),
			array('allow',
				'actions'=>array('adminView','create','send','update','admin','showRecipients','delete'),
				'expression'=>"Yii::app()->user->isAdmin()",
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	// http://www.yiiframework.com/wiki/20/how-to-generate-web-feed-for-an-application/
	public function actionFeed()
	{
		Yii::import('application.vendors.*');
		require_once 'Zend/Loader/Autoloader.php';
		spl_autoload_unregister(array('YiiBase','autoload')); 
		spl_autoload_register(array('Zend_Loader_Autoloader','autoload')); 
		spl_autoload_register(array('YiiBase','autoload'));

		$newsletters = Newsletter::model()->getNewslettersForRSS();
		// convert to the format needed by Zend_Feed
		$entries=array();
		foreach($newsletters as $newsletter)
		{
			$date = new DateTime($newsletter->published);
			$entries[]=array(
				'title'=>$newsletter->subject,
				'link'=>Yii::app()->createAbsoluteUrl('newsletter/view',array('id'=>$newsletter->id)),
				'description'=>$newsletter->body,
				'lastUpdate'=>$date->getTimestamp(),
			);
		}
		// generate and render RSS feed
		$feed=Zend_Feed::importArray(array(
			'title'			=> Config::model()->findByPk('siglas')->value.' '.__('Newsletters'),
			'description'	=> Config::model()-> getObservatoryName(),
			'link'			=> Yii::app()->createUrl('newsletter'),
			'image'			=> Yii::app()->createAbsoluteUrl('files/logo.png'),
			'charset'		=> 'UTF-8',
			'entries'		=> $entries,      
			),
			'rss'
		);
		$feed->send();  
	}

	public function actionView($id)
	{
		$this->pageTitle = Config::model()->findByPk('siglas')->value.' '.__('Newsletter');
		$this->layout='//layouts/column1';
		$model=$this->loadModel($id);
		if($model->sent != 2)
			$this->redirect(array('site/index'));
		
		$this->render('view',array(
			'model'=>$model,
		));
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionAdminView($id)
	{
		$model=$this->loadModel($id);
		if($model->sent == 0){
	        $sql = "SELECT id FROM user WHERE is_active = 1";
	        $cnt = "SELECT COUNT(*) FROM ($sql) subq";
			$count = Yii::app()->db->createCommand($cnt)->queryScalar();
		}else{
			$count=count(explode(',',$model->recipients));
		}


		$this->render('adminView',array(
			'model'=>$model,
			'total_recipients'=>$count,
		));
	}

	public function actionShowRecipients($id=Null)
	{
		$model=Null;
		if($id)
			$model=$this->loadModel($id);
		if($model && $model->sent != 0)
			echo $this->renderPartial('showRecipients',array('recipients'=>$model->recipients,'draft'=>Null),false,true);
		else{
			$users = Yii::app()->db->createCommand()
					->select('email')
					->from('user')
					->where('is_active = 1')
					->queryAll();

			$result='';
			foreach($users as $recipient)
			    $result=$result.$recipient['email'].', ';
			echo $this->renderPartial('showRecipients',array('recipients'=>substr_replace($result ,"",-2),'draft'=>1),false,true);
		}
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Newsletter;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Newsletter']))
		{
			$model->attributes=$_POST['Newsletter'];

			$model->created = date('c');
			$model->sent=0;
			$model->sender=Yii::app()->user->getUserID();
			$model->body = htmLawed::hl($model->body, array('safe'=>1, 'deny_attribute'=>'script, class, id'));
			
			if($model->save())
				$this->redirect(array('adminView','id'=>$model->id));
		}

        $sql = "SELECT id FROM user WHERE is_active = 1";
        $cnt = "SELECT COUNT(*) FROM ($sql) subq";
		$count = Yii::app()->db->createCommand($cnt)->queryScalar();  

		$this->render('create',array(
			'model'=>$model,
			'total_recipients'=>$count,
		));
	}

	/**
	 * Preview email
	 */
	public function actionSend($id)
	{
		$model=$this->loadModel($id);
		$model->setScenario('send');

 		$mailer = new Mailer();

		$users = Yii::app()->db->createCommand()
				->select('email')
				->from('user')
				->where('is_active = 1')
				->queryAll();

		$addresses = array();
		foreach($users as $recipient){
		    $model->recipients=$model->recipients.$recipient['email'].', ';
		    $addresses[] = trim($recipient['email']);
		}
		$model->recipients = substr_replace($model->recipients ,"",-2);
		$model->sender=Yii::app()->user->getUserID();
		$mailer->SetFrom($model->sent_as, Config::model()->findByPk('siglas')->value);
		$mailer->Subject=$model->subject;
		$mailer->Body=$model->body;

		if($mailer->sendBatches($addresses)){
			$model->sent=2;
			$model->published = date('c');
			Yii::app()->user->setFlash('success',__('Email sent OK'));
			Log::model()->write('Newsletter', __('Newsletter published'), $model->id);
		}else{
			$model->published = Null;
			$model->sent=1;
			Yii::app()->user->setFlash('error',__('Error while sending email').'<br />"'.$mailer->ErrorInfo.'"');
		}
		$model->save();
		echo 1;
		//$this->redirect(array('adminView','id'=>$model->id));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$this->pageTitle=CHtml::encode(Config::model()->findByPk('siglas')->value.' '.__('Newsletter'));
		$model=new Newsletter('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Newsletter']))
			$model->attributes=$_GET['Newsletter'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Newsletter']))
		{
			$model->attributes=$_POST['Newsletter'];
			if($model->save())
				$this->redirect(array('adminView','id'=>$model->id));
		}

        $sql = "SELECT id FROM user WHERE is_active = 1";
        $cnt = "SELECT COUNT(*) FROM ($sql) subq";
		$count = Yii::app()->db->createCommand($cnt)->queryScalar();  

		$this->render('update',array(
			'model'=>$model,
			'total_recipients'=>$count,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */

	public function actionDelete($id)
	{
		$model=$this->loadModel($id);
		if($model->sent == 0)	// admin can delete a draft
			$model->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */

	public function actionIndex()
	{
		$this->layout='//layouts/column1';
		$this->pageTitle = Config::model()->findByPk('siglas')->value.' '.__('Newsletter');
		$criteria=new CDbCriteria;
		$criteria->addCondition('published IS NOT NULL');
		$criteria->order = 'published DESC';

		$dataProvider=new CActiveDataProvider('Newsletter',array('criteria'=>$criteria,'pagination'=>array('pageSize'=>1)));
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Newsletter the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Newsletter::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Newsletter $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='newsletter-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/newsletter/_form.php
<?php

/**
 * OCAX -- Citizen driven Observatory software
 * Copyright (C) 2014 OCAX Contributors. See AUTHORS.

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* @var $this NewsletterController */
/* @var $model Newsletter */

?>

<style>
#recipients_link{
	cursor:pointer;
	text-decoration:underline;
}
</style>

<script src="<?php echo Yii::app()->request->baseUrl; ?>/scripts/jquery.bpopup-0.9.4.min.js"></script>
<script>
function showRecipients(){
	$.ajax({
		url: '<?php echo Yii::app()->request->baseUrl; ?>/newsletter/showRecipients',
		type: 'GET',
		success: function(data){
			if(data != 0){
				$("#recipients_popup_body").html(data);
				$('#recipients_popup').bPopup({
                    modalClose: false
					, follow: ([false,false])
					, speed: 10
					, positionStyle: 'absolute'
					, modelColor: '#ae34d5'
                });
			}
		},
		error: function() {
			alert("Error on show recipients");
		}
	});
}
</script>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'newsletter-form',
	'enableAjaxValidation'=>false,
)); ?>

	<div class="title"><?php echo __('Send bulk email')?></div>


	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php $model->sent_as=Config::model()->findByPk('emailNoReply')->value;?>
		<?php echo '<p><b>'.__('Sent as').':</b> '.$model->sent_as.'</p>'; ?>
		<?php echo $form->hiddenField($model,'sent_as'); ?>
	</div>

	<div class="row">
		<p>
		<b><?php echo $total_recipients.' '.__('BCC Recipients');?></b>: <span id="recipients_link" onClick="js:showRecipients();">
		<?php echo __('Show');?>
		</span>
		</p>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'subject'); ?>
		<?php echo $form->textField($model,'subject',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'subject'); ?>
	</div>


	<div class="row">
		<?php echo $form->labelEx($model,'body'); ?>
		<?php
		$settings = array('theme_advanced_buttons1' => "undo,redo,|,bold,italic,underline,|,justifyleft,justifycenter,
														justifyright,|,bullist,numlist,|,outdent,indent,|,
														link,unlink,|,image",
							'convert_urls'=>true,
							'relative_urls'=>false,
							'remove_script_host'=>false,
							'theme_advanced_resize_horizontal' => 0,
							'theme_advanced_resize_vertical' => 0,
							'theme_advanced_resizing_use_cookie' => false,
							'width'=>'100%',
							'valid_elements' => "@[style],p,span,a[href|target=_blank],strong/b,div[align],br,ul,ol,li,img[src]",
				);
		if(Config::model()->findByPk('htmlEditorUseCompressor')->value)
			$settings['useCompression']=true;
		else
			$settings['useCompression']=false;
			
		$init = array(
		    'model' => $model,
		    'attribute' => 'body',
		    // Optional config
		    'compressorRoute' => 'tinyMce/compressor',
		    //'spellcheckerUrl' => array('tinyMce/spellchecker'),
		    // or use yandex spell: http://api.yandex.ru/speller/doc/dg/tasks/how-to-spellcheck-tinymce.xml
		    'spellcheckerUrl' => 'http://speller.yandex.net/services/tinyspell',
			'settings' => $settings,
		);
		if(!Config::model()->findByPk('htmlEditorUseCompressor')->value)
				unset($init['compressorRoute']);

		$this->widget('ext.tinymce.TinyMce', $init);
		echo $form->error($model,'body');
	?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton(__('Preview')); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

<div id="recipients_popup" class="modal" style="width:650px;">
	<i class='icon-cancel-circled modalWindowButton bClose'></i>
	<div id="recipients_popup_body"></div>
</div>

protected/views/newsletter/_search.php
<?php

/**
 * OCAX -- Citizen driven Municipal Observatory software
 * Copyright (C) 2013 OCAX Contributors. See AUTHORS.

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* @var $this NewsletterController */
/* @var $model Newsletter */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'recipients'); ?>
		<?php echo $form->textField($model,'recipients',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'body'); ?>
		<?php echo $form->textField($model,'body',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton(__('Search')); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/newsletter/adminView.php
<?php

/**
 * OCAX -- Citizen driven Observatory software
 * Copyright (C) 2014 OCAX Contributors. See AUTHORS.

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* @var $this NewsletterController */
/* @var $model Newsletter */


$this->menu=array(
	array('label'=>__('Create bulk email'), 'url'=>array('create')),
	array('label'=>__('Manage bulk email'), 'url'=>array('admin')),
);

if($model->sent == 0){
	$delete = array(
			array('label'=>__('Delete draft'), 'url'=>'#', 'linkOptions'=>array(
																			'submit'=>array('delete',
																					'id'=>$model->id
																			),
																			'csrf'=>true,
																			'confirm'=>__('Are you sure you want to delete this item?'))
																		));
	array_splice( $this->menu, 0, 0, $delete );
}
$this->inlineHelp=':manual:newsletter:adminview';
?>

<style>           
.outer{width:100%; padding: 0px; float: left;}
.left{width: 38%; float: left;  margin: 0px;}
.right{width: 58%; float: left; margin: 0px;}
.clear{clear:both;}

#recipients_link{
	cursor:pointer;
	text-decoration:underline;
}
</style>

<script src="<?php echo Yii::app()->request->baseUrl; ?>/scripts/jquery.bpopup-0.9.4.min.js"></script>
<script>
function showRecipients(){
	$.ajax({
		url: '<?php echo Yii::app()->request->baseUrl; ?>/newsletter/showRecipients/<?php echo $model->id?>',
		type: 'GET',
		success: function(data){
			if(data != 0){
				$("#recipients_popup_body").html(data);
				$('#recipients_popup').bPopup({
                    modalClose: false
					, follow: ([false,false])
					, speed: 10
					, positionStyle: 'absolute'
					, modelColor: '#ae34d5'
                });
			}
		},
		error: function() {
			alert("Error on show recipients");
		}
	});
}
function send(){
	$('input').prop('disabled', true);
	$('#loading').show();
	
	$.ajax({
		url: '<?php echo Yii::app()->request->baseUrl;?>/newsletter/send/<?php echo $model->id?>',
		type: 'POST',
		data: { 'YII_CSRF_TOKEN' : '<?php echo Yii::app()->request->csrfToken; ?>' },
		error: function() {
			alert("Error on send email");
		},
		complete: function(){ window.location.reload(); }
	});
}
</script>

<h1 class="sub_title"><?php echo CHtml::encode($model->subject);?></h1>
<div class="email">

<div class="details outer">	
<div class="form">

<div class="left">
	<p style="margin-bottom:5px">
	<b><?php echo CHtml::encode($model->getAttributeLabel('created'));?>:</b>
	<?php echo CHtml::encode($model->created); ?><br />

	<b><?php echo CHtml::encode($model->getAttributeLabel('sent'));?>:</b>
	<?php echo CHtml::encode($model->getHumanSentValues($model->sent));?><br />


	<b><?php echo CHtml::encode($model->getAttributeLabel('sender'));?>:</b>
	<?php echo CHtml::encode($model->sender0->fullname);?><br />

	<b><?php echo CHtml::encode($model->getAttributeLabel('sent_as')); ?>:</b>
	<?php echo CHtml::encode($model->sent_as); ?><br />

	<b><?php echo $total_recipients.' '.__('BCC Recipients');?></b>:
	<span id="recipients_link" onClick="js:showRecipients();">
	<?php echo __('Show');?>
	</span>
	</p>
</div>

<div class="right" style="margin-top:15px">

<?php if($model->sent == 0){

echo CHtml::button(__('Edit draft'), array('onclick'=>'js:document.location.href="'.Yii::app()->request->baseUrl.'/newsletter/update/'.$model->id.'"'));
echo CHtml::button(__('Publish now'), array('onclick'=>'js:send();','style'=>'margin-left:100px;'));
echo '<img id="loading" src="'.Yii::app()->request->baseUrl.'/images/small_loading.gif" style="vertical-align:middle;margin-left:15px;display:none"/>';

}?>
</div>
</div>
</div>

<div class="clear"></div>
<p><?php echo $model->body; ?></p>
</div>

<div id="recipients_popup" class="modal" style="width:650px;">
	<i class='icon-cancel-circled modalWindowButton bClose'></i>
	<div id="recipients_popup_body"></div>
</div>


<?php if(Yii::app()->user->hasFlash('success')):?>
    <div class="flash-success">
		<?php echo Yii::app()->user->getFlash('success');?>
    </div>
<?php endif; ?>
<?php if(Yii::app()->user->hasFlash('error')):?>
    <div class="flash-error">
		<?php echo Yii::app()->user->getFlash('error');?>
    </div>
<?php endif; ?>