protected/controllers/UserController.php
<?php
/**
 * OCAX -- Citizen driven Observatory software
 * Copyright (C) 2014 OCAX Contributors. See AUTHORS.

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

class UserController extends Controller
{

	public $layout='//layouts/column1';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete, disable, enable, optout', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('panel','update','block','optout'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('view','admin','delete','updateRoles','enable'),
				'expression'=>"Yii::app()->user->isAdmin()",
			),
			array('allow',
				'actions'=>array('disable'),
				'expression'=>"Yii::app()->user->isManager() || Yii::app()->user->isAdmin()",
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * User's panel.
	 */
	public function actionPanel()
	{
		$this->pageTitle=CHtml::encode(Config::model()->findByPk('siglas')->value.' '.__('My page'));
		$user=User::model()->findByAttributes(array('username'=>Yii::app()->user->id));
		if ($user===null){
			throw new CHttpException(404,'The requested User does not exist.');
		}
		$userid=Yii::app()->user->getUserID();
		$enquirys=new CActiveDataProvider('Enquiry', array(
			'criteria'=>array(
				'condition'=>"user=$userid",
			),
			'sort'=>array('defaultOrder'=>'modified DESC'),
		));

		$subscribed=new CActiveDataProvider('Enquiry',array(
			'criteria'=>array(
				'with'=>array('subscriptions'),
				'condition'=>'	subscriptions.enquiry = t.id AND
								subscriptions.user = '.$userid.' AND
								t.user != '.$userid.' AND
								( t.team_member != '.$userid.' || t.team_member IS NULL )',
				'together'=>true,
			),
			'sort'=>array('defaultOrder'=>'t.modified DESC'),
		));
		
		if(Yii::app()->user->isAdmin()){
			$config = Config::model();
			
			// update schema.
			$schema = new Schema;
			if(!$schema->isSchemaUptodate($config->getOCAxVersion())){
				$schema->migrate();
				$postInstallChecked = $config->findByPk('siteConfigStatusPostInstallChecked');
				$postInstallChecked->value = 0;
				$postInstallChecked->save();			
			}
			// check for OCAx updates once a week
			$latest_version_file = Yii::app()->basePath.'/runtime/latest.ocax.version';
			if (!file_exists($latest_version_file))
				$config->updateVersionInfo();
			else{
				$date = new DateTime();
				if( $date->getTimestamp() - filemtime($latest_version_file) > 86400 ) // 604800 a week
					$config->updateVersionInfo();
			}
			if($config->isOCAXUptodate())
				$config->updateSiteConfigurationStatus('siteConfigStatusUptodate', 1);
			else
				$config->updateSiteConfigurationStatus('siteConfigStatusUptodate', 0);
		}
		$this->render('panel',array(
				'model'=>$this->loadModel($user->id),
				'enquirys'=>$enquirys,
				'subscribed'=>$subscribed,
		));
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{

		$enquirys=new CActiveDataProvider('Enquiry', array(
			'criteria'=>array(
				'condition'=>"user=$id",
				'order'=>'created ASC',
			),
			'pagination'=>array(
				'pageSize'=>20,
			),
		));

		$this->layout='//layouts/column2';
		$this->render('view',array(
			'model'=>$this->loadModel($id),
			'enquirys'=>$enquirys,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate()
	{
		$model=User::model()->findByAttributes(array('username'=>Yii::app()->user->id));
		if ($model===null){
			throw new CHttpException(404,'The requested User does not exist.');
		}
		$email = $model->email;
		$language = $model->language;

		if(isset($_POST['User']))
		{
			$model->scenario = 'update_user';
			$model->attributes=$_POST['User'];

			if($_POST['User']['new_password'] || $_POST['User']['password_repeat']){

				$model->new_password=$_POST['User']['new_password'];
				$model->password_repeat=$_POST['User']['password_repeat'];
				$model->scenario = 'change_password';

				if(!$model->validate()){
					$this->render('update',array('model'=>$model,));
					Yii:app()->end();
				}
				$model->salt=$model->generateSalt();
				$model->password = $model->hashPassword($model->new_password,$model->salt);
			}
			if ($email != $model->email){
				$model->is_active=0;
			}
			if($model->save()){
				Yii::app()->language = $model->language;
				$cookie = new CHttpCookie('lang', $model->language);
				$cookie->expire = time()+60*60*24*180;
				Yii::app()->request->cookies['lang'] = $cookie;

				Yii::app()->user->setFlash('success', __('Changes saved Ok'));
				if(!$model->is_active)
					$this->redirect(array('/site/sendActivationCode'));
				else
					$this->redirect(array('panel'));
			}
		}
		$this->render('update',array(
			'model'=>$model,
		));
	}
/*
	public function actionBlock($id)
	{
		$blocked_user=User::model()->findByAttributes(array('username'=>$id));
		if(!$blocked_user)
			$this->redirect(array('panel'));
		if($blocked_user->username != Yii::app()->user->id){
			$userid=Yii::app()->user->getUserID();
			if(isset($_GET['confirmed'])){
				$block = new BlockUser;
				if(! $block->findByAttributes(array('user'=>$userid, 'blocked_user'=>$blocked_user->id))){

					$block->user=$userid;
					$block->blocked_user=$blocked_user->id;
					$block->save();
				}
				Yii::app()->user->setFlash('success', $blocked_user->fullname.' '.__('is blocked'));
			}else{
				if(! BlockUser::model()->findByAttributes(array('user'=>$userid, 'blocked_user'=>$blocked_user->id)))
					Yii::app()->user->setFlash('prompt_blockuser', $blocked_user->fullname.'|'.$id);
			}
		}
		$this->redirect(array('panel'));
	}
*/
	public function actionUpdateRoles($id)
	{
		$this->layout='//layouts/column2';
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->scenario = 'update_roles';
			$model->attributes=$_POST['User'];
			if($model->save()){
				Log::model()->write('User',__('User permissiones changed for').' "'.$model->username.'"',$model->id);
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('updateRoles',array(
			'model'=>$model,
		));
	}

	/**
	 * A disabled user cannot login
	 * ajax call from enquiry/manage
	 */
	public function actionDisable($id)
	{
		$model=$this->loadModel($id);
		$model->disableUser();
		if(Yii::app()->request->isAjaxRequest){
			Yii::app()->user->setFlash('success', __('User disabled'));
			echo 1;
		}else
			$this->redirect(array('view','id'=>$model->id));
	}

	public function actionEnable($id)
	{
		$model=$this->loadModel($id);
		$model->enableUser();
		$this->redirect(array('view','id'=>$model->id));
	}

	/*
	 * The user deletes his account
	 * We don't delete the database entry because it might be referenced by other models
	 */
	public function actionOptout()
	{
		if(Yii::app()->user->isGuest){
			$this->redirect(array('site/index'));
			Yii:app()->end();
		}
		$model=$this->loadModel(Yii::app()->user->getUserID());

		$username = $model->username;
		$model->smudgeUser();

		Yii::app()->user->logout();
		//Yii::app()->user->setFlash('success', __('Your profile has been deleted.'));
		$this->redirect(Yii::app()->homeUrl);
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$model=$this->loadModel($id);
		$model->smudgeUser();
		Yii::app()->user->setFlash('success', __('User deleted'));
		$this->redirect(array('/user/admin'));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new User('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['User']))
			$model->attributes=$_GET['User'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=User::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='user-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/user/_notActiveInfo.php
<?php
/**
 * OCAX -- Citizen driven Municipal Observatory software
 * Copyright (C) 2013 OCAX Contributors. See AUTHORS.

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
?>


<?php
$str=__('USER_NOT_ACTIVE_INFO');

$str=preg_replace( '/%s/', $model->email, $str, 1 );
$str=preg_replace( '/%s/', CHtml::link(__('click here'), array('site/sendWelcomeText')), $str, 1 );
$str=preg_replace( '/%s/', $model->email, $str, 1 );
$str=preg_replace( '/%s/', CHtml::link(__('click here'), array('user/update')), $str, 1 );

echo $str;
?>

protected/views/user/_search.php
<?php
/**
 * OCAX -- Citizen driven Municipal Observatory software
 * Copyright (C) 2013 OCAX Contributors. See AUTHORS.

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* @var $this UserController */
/* @var $model User */
/* @var $form CActiveForm */
?>

<style>
.outer{ width: 100% }

</style>

<div class="wide form" style="width:100%;margin-top:15px;">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

<div style="float:left;width:50%">

	<div class="row">
		<?php echo $form->label($model,'username',array('style'=>'white-space: nowrap;')); ?>
		<?php echo $form->textField($model,'username',array('style'=>'width:200px')); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'fullname',array('style'=>'white-space: nowrap;')); ?>
		<?php echo $form->textField($model,'fullname',array('style'=>'width:200px')); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'email',array('style'=>'white-space: nowrap;')); ?>
		<?php echo $form->textField($model,'email',array('style'=>'width:200px')); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton(__('Search')); ?>
	</div>

</div>
<div style="float:right;width:24%">

	<div class="row">
		<?php echo $form->label($model,'is_team_member'); ?>
		<?php echo $form->textField($model,'is_team_member',array('size'=>5)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'is_manager'); ?>
		<?php echo $form->textField($model,'is_manager',array('size'=>5)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'is_admin'); ?>
		<?php echo $form->textField($model,'is_admin',array('size'=>5)); ?>
	</div>

</div>
<div style="float:right;width:24%">

	<div class="row">
		<?php echo $form->label($model,'is_active'); ?>
		<?php echo $form->textField($model,'is_active',array('size'=>5)); ?>
	</div>

	<?php if(Config::model()->findByPk('membership')->value){ ?>
	<div class="row">
		<?php echo $form->label($model,'is_socio'); ?>
		<?php echo $form->textField($model,'is_socio',array('size'=>5)); ?>
	</div>
	<?php } ?>

	<div class="row">
		<?php echo $form->label($model,'is_editor'); ?>
		<?php echo $form->textField($model,'is_editor',array('size'=>5)); ?>
	</div>

</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->
<div style="clear:both"></div>

protected/views/user/_view.php
<?php
/**
 * OCAX -- Citizen driven Municipal Observatory software
 * Copyright (C) 2013 OCAX Contributors. See AUTHORS.

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
 
/* @var $this UserController */
/* @var $data User */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('username')); ?>:</b>
	<?php echo CHtml::encode($data->username); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('fullname')); ?>:</b>
	<?php echo CHtml::encode($data->fullname); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('email')); ?>:</b>
	<?php echo CHtml::encode($data->email); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('joined')); ?>:</b>
	<?php echo CHtml::encode($data->joined); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('is_socio')); ?>:</b>
	<?php echo CHtml::encode($data->is_socio); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('is_team_member')); ?>:</b>
	<?php echo CHtml::encode($data->is_team_member); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('is_editor')); ?>:</b>
	<?php echo CHtml::encode($data->is_editor); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('is_manager')); ?>:</b>
	<?php echo CHtml::encode($data->is_manager); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('is_admin')); ?>:</b>
	<?php echo CHtml::encode($data->is_admin); ?>
	<br />

</div>

protected/views/user/admin.php
<?php
/**
 * OCAX -- Citizen driven Observatory software
 * Copyright (C) 2013 OCAX Contributors. See AUTHORS.

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* @var $this UserController */
/* @var $model User */

Yii::app()->clientScript->registerScript('search', "
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('user-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>
<script>
function toggleSearchOptions(){
	if ($("#searchOptions").is(":visible")){
		$("#searchOptionsToggle").html("<i class='icon-search-circled'></i>");
		$("#searchOptions").slideUp();
	}else{
		$("#searchOptionsToggle").html("<i class='icon-cancel-circled'></i>");
		$("#searchOptions").slideDown();
	}
}
</script>
<div style="position:relative;" >
	<div class="teamMenu" onCLick="js:window.location.href = '<?php echo $this->createUrl('/user/panel');?>';">
		<i class="icon-home"></i>
	</div>
</div>
<div style="position:relative; right:40px" >
	<div class="teamMenu" onCLick="js:viewLog('User');return false;">
		<i class="icon-book"></i>
	</div>
</div>
<div style="position:relative; right:80px" >
	<div class="teamMenu" onCLick="js:showHelp('<?php echo getInlineHelpURL(":manual:user:admin");?>');return false;">
		<i class="icon-help-circled"></i>
	</div>
</div>
<div style="position:relative; right:120px">
	<div id="searchOptionsToggle" class="color" onCLick="js:toggleSearchOptions();return false;">
		<i class="icon-search-circled"></i>
	</div>
</div>
<?php $this->widget('InlineHelp'); ?>
<?php $this->widget('ViewLog'); ?>

<h1><?php echo __('Users and roles');?></h1>

<div id="searchOptions" class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'htmlOptions'=>array('class'=>'pgrid-view'),
	'cssFile'=>Yii::app()->request->baseUrl.'/css/pgridview.css',
	'id'=>'user-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'username',
		//'fullname',
		'email',
		//'is_socio',
		'is_team_member',
		'is_editor',
		'is_manager',
		'is_admin',
		/*
		'joined',
		'activationcode',
		'activationstatus',
		*/
		array(
			'class'=>'CButtonColumn',
			'template'=>'{view} {update}',
			'buttons'=>array(
				'update' => array(
					'label'=>'Update',
		            'url'=>'Yii::app()->createUrl("user/updateRoles", array("id"=>$data->id))',
				),
			),
		),
	)
));?>


<?php if(Yii::app()->user->hasFlash('success')):?>
	<script>
		$(function() { setTimeout(function() {
			$('.flash-success').slideUp('fast');
    	}, 5000);
		});
	</script>
    <div class="flash-success">
		<?php echo Yii::app()->user->getFlash('success');?>
    </div>
<?php endif; ?>

protected/views/user/index.php
<?php
/**
 * OCAX -- Citizen driven Municipal Observatory software
 * Copyright (C) 2013 OCAX Contributors. See AUTHORS.

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* @var $this UserController */
/* @var $dataProvider CActiveDataProvider */


$this->menu=array(
	array('label'=>'Create User', 'url'=>array('create')),
	array('label'=>'Manage User', 'url'=>array('admin')),
);
?>

<h1>Users</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/user/update.php
<?php
/**
 * OCAX -- Citizen driven Municipal Observatory software
 * Copyright (C) 2013 OCAX Contributors. See AUTHORS.

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
 
/* @var $this UserController */
/* @var $model User */

$languages = getLanguagesArray();
$solicit_membership = Config::model()->findByPk('membership')->value;
?>

<script>
function optout(){
	retVal = confirm("<?php echo __('Are you sure you want to delete your account?');?>");
	if( retVal == false ){
		return;
	}
	$.ajax({
		url: '<?php echo Yii::app()->request->baseUrl; ?>/user/optout',
		type: 'POST',
		data: { 'YII_CSRF_TOKEN' : '<?php echo Yii::app()->request->csrfToken; ?>' },
		success: function(){
			window.location.href = '<?php echo Yii::app()->request->baseUrl; ?>';					
		},
		error: function() { alert("error on opt out"); },
	});
}
</script>

<?php if($languages || $solicit_membership) { ?>
	<style>           
		.outer{width:100%; padding: 0px; float: left; margin-top:10px;}
		.left{width: 32%; float: left;  margin: 0px; margin-left:20px;}
		.middle{width: 32%; float: left;  margin: 0px; margin-left:40px;}
		.right{width: 22%; float: left; margin: 0px;}
		.clear{clear:both;}
	</style>
<?php } else { ?>
	<style>           
		.outer{width:100%; padding: 0px; float: left; margin-top:10px;}
		.left{width: 50%; float: left;  margin: 0px; margin-left:20px; }
		.middle{width: 45%; float: left;  margin: 0px;}
		.clear{clear:both;}
	</style>
<?php } ?>

<div style="margin:-10px 0 55px 0;">
<span id="datos_usuario" style="margin-top:-15px;cursor:auto;float:left"></span>
<h1 style="float:left"><?php echo __('Change your user information')?></h1>
<span class="link" style="float:right" onclick="js:optout();"><?php echo __('Delete my user account');?></span>
</div>
<div style="clear:both"></div>


<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'user-form',
	'enableAjaxValidation'=>false,
)); ?>

<div class="outer">
<div class="left">

	<p class="sub_title"><?php echo __('Your information')?></p>

	<?php /*echo $form->errorSummary($model);*/ ?>

	<div class="row">
		<?php echo $form->labelEx($model,'fullname'); ?>
		<?php echo $form->textField($model,'fullname',array('size'=>30,'maxlength'=>64)); ?>
		<?php echo $form->error($model,'fullname'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'email'); ?>
		<?php echo $form->textField($model,'email',array('size'=>30,'maxlength'=>64)); ?>
		<?php echo $form->error($model,'email'); ?>
	</div>

</div>
<div class="middle">
<p class="sub_title"><?php echo __('Change password');?></p>

	<div class="row">
		<?php echo $form->labelEx($model,'new_password'); ?>
		<?php echo $form->passwordField($model,'new_password',array('autocomplete'=>'off'));	?>
		<?php echo $form->error($model,'new_password'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'password_repeat'); ?>
		<?php echo $form->passwordField($model,'password_repeat',array('autocomplete'=>'off')); ?>
		<?php echo $form->error($model,'password_repeat'); ?>
	</div>
</div>

<?php if($languages || $solicit_membership) { ?>
<div class="right">
<p class="sub_title" class="sub_title"><?php echo __('Details');?></p>
	<?php
		if($languages){
			echo '<div class="row">';
			echo $form->labelEx($model,'language');
			echo '<div class="hint">'.__('Your preferred language').'</div>';
			echo $form->dropDownList($model, 'language', $languages );
			echo '</div>';
		}	
	?>
	
	<?php if($solicit_membership){ ?>
	<div class="row">
		<label><?php echo __('Yes, I want to be a member').' '.$form->checkBox($model,'is_socio', array('checked'=>$model->is_socio));?></label>
		<a href="#" onClick="js:$('#membership_means').slideDown('fast');"><?php echo __('What does this mean?');?></a>
	</div>
	<?php } ?>
</div>
<?php } ?>

</div>
<div class="clear"></div>

	<?php if($solicit_membership){ ?>
	<div id="membership_means" style="display:none" class="horizontalRule">
	<p><?php echo  __('MEMBERSHIP_MSG'); ?></p>
	</div>
	<?php } ?>

	<div class="row buttons" style="text-align:center;padding-top:20px;">
		<?php echo CHtml::submitButton(__('Save')); ?>
		<input type="button" onclick="window.location='<?php echo Yii::app()->request->baseUrl;?>/user/panel'" value="<?php echo __('Cancel')?>" />
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

<?php if(Yii::app()->user->hasFlash('success')):?>
	<script>
		$(function() { setTimeout(function() {
			$('.flash-success').slideUp('fast');
    	}, 5000);
		});
	</script>
    <div class="flash-success">
		<?php echo Yii::app()->user->getFlash('success');?>
    </div>
<?php endif; ?>