protected/models/Config.php
<?php

/**
 * OCAX -- Citizen driven Observatory software
 * Copyright (C) 2014 OCAX Contributors. See AUTHORS.

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * This is the model class for table "config".
 *
 * The followings are the available columns in table 'config':
 * @property string $parameter
 * @property string $value
 * @property string $description
 */
class Config extends CActiveRecord
{
	/* If any of these return 0, then
	 * $this->findByPk('siteConfigStatus') is set to 1 and
	 * config/pendingConfiguraton (aka Admin Tasks) is rendered on user/panel
	 */
	private $autoCheckParams = array(
						'siteConfigStatusLanguage',
						'siteConfigStatusEmail',
						'siteConfigStatusInitials',
						'siteConfigStatusObservatoryName',
						'siteConfigStatusAdministrationName',
						'siteConfigStatusBudgetDescriptionsImport',
						'siteConfigStatusEmailTemplates',
						'siteConfigStatusUptodate',
					);
	
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Config the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'config';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('value', 'required', 'on'=>'cannotBeEmpty'),
			array('parameter, description', 'required'),
			array('value', 'length', 'max'=>255),
			array('value','validateLanguage', 'on'=>'language'),
			array('value', 'url', 'on'=>'URL', 'allowEmpty'=>true),
			array('value','validateCurrenyCollocation', 'on'=>'currenyCollocation'),
			array('value','validateSiteColor', 'on'=>'siteColor'),
			array('value', 'email', 'on'=>'email', 'allowEmpty'=>false),
			array('value', 'numerical', 'on'=>'positiveNumber', 'allowEmpty'=>false, 'min'=>1),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			//array('parameter, value, description', 'safe', 'on'=>'search'),
		);
	}

	public function validateLanguage($attribute,$params)
	{
		if($this->$attribute === ""){
				$this->addError($attribute, __('Please define a language'));
				return;
		}
		$available_langs = Yiibase::getPathOfAlias('application.messages');
		$languages = explode(',', $this->$attribute);
		foreach($languages as $language){
			if(!is_dir($available_langs.'/'.$language)){
				$this->addError($attribute, $language.' '.__('is not a valid language.'));
			}
		}
	}

	public function validateCurrenyCollocation($attribute,$params)
	{
		if($this->$attribute === ""){
				$this->addError($attribute, __('Missing value'));
				return;
		}
		$this->$attribute = trim($this->$attribute);
		if(stristr($this->$attribute, 'n') === FALSE) {
			$this->addError($attribute, __("Character 'n' is missing."));
		}
	}

	public function validateSiteColor($attribute,$params)
	{
		$color = $this->$attribute;
		if(!(preg_match('/^[a-f0-9]{6}$/i', $color) && strlen($color)==6))
			$this->addError($attribute, __("Expecting a 6 digit web color"));
		return;
	}

	/*
	 * These are initial configuration parameters.
	 * When OCAx is installed, they are set to 0
	 * Admin user is alerted views/user/panel
	 * Alert is removed when these params have been set.
	 */ 
	protected function afterSave()
	{
		if($this->parameter == 'languages'){
			$record = $this->findByPk('siteConfigStatusLanguage');
			$record->value = 1;
			$record->save();
			return $this->_updateSiteConfigurationStatus();
		}
		elseif($this->parameter == 'siglas'){
			$record = $this->findByPk('siteConfigStatusInitials');
			$record->value = 1;
			$record->save();
			return $this->_updateSiteConfigurationStatus();
		}
		elseif($this->parameter == 'observatoryName1' || $this->parameter == 'observatoryName2'){
			$record = $this->findByPk('siteConfigStatusObservatoryName');
			$record->value = 1;
			$record->save();
			return $this->_updateSiteConfigurationStatus();
		}
		elseif($this->parameter == 'administrationName'){
			$record = $this->findByPk('siteConfigStatusAdministrationName');
			$record->value = 1;
			$record->save();
			return $this->_updateSiteConfigurationStatus();
		}
	}

	private function _updateSiteConfigurationStatus()
	{
		$siteConfigStatus = $this->findByPk('siteConfigStatus');

		$sql = "SELECT COUNT(*) FROM budget_desc_common";
		if(intval(Yii::app()->db->createCommand($sql)->queryScalar()) != 0){
			$param = $this->findByPk('siteConfigStatusBudgetDescriptionsImport');
			if($param->value != 1){
				$param->value =1;
				$param->save();
			}
		}
		foreach($this->autoCheckParams as $p){
			if($this->findByPk($p)->value == 0){
				$siteConfigStatus->value=0;
				$siteConfigStatus->save();
				return 0;
			}
		}
		$siteConfigStatus->value=1;
		$siteConfigStatus->save();
		return 1;
	}

	public function updateSiteConfigurationStatus($param=Null, $value=Null)
	{
		if($param !==Null && $value !== NUll){
			$record = $this->findByPk($param);
			$record->value = $value;
			$record->save();
		}
		return $this->_updateSiteConfigurationStatus();
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array();
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'parameter' => __('Parameter'),
			'value' => __('Value'),
			'description' => __('Description'),
		);
	}

	public function getSiteTitle()
	{
		$title=str_replace('%s', '<span id="observatoryName2">'.$this->findByPk('observatoryName2')->value.'</span>', $this->findByPk('observatoryName1')->value);
		return str_replace('#', '<br />', $title);
	}

	public function getObservatoryName()
	{
		$title = str_replace('%s', $this->findByPk('observatoryName2')->value, $this->findByPk('observatoryName1')->value);
		$title = str_replace('#', ' ', $title);
		return strip_tags($title);
	}

	public function getObservatoryInitials()
	{
		return $this->findByPk('siglas')->value;
	}


	public function getSiteColor()
	{
		if($color = Config::model()->findByPk('siteColor'))
			return $color->value;
		return 'a1a150';
	}

	public function isSiteMultilingual()
	{
		$languages=explode(',', $this->findByPk('languages')->value);
		if(isset($languages[1]))
			return 1;
		return 0;
	}

	public function isSocialNonFree()
	{
		if(Config::model()->findByPk('schemaVersion')->value == 0)
			return 0;
		return Config::model()->findByPk('socialActivateNonFree')->value;
	}

	public function updateVersionInfo(){
		$context = stream_context_create(array(
			'http' => array(
			'header' => 'Content-type: application/x-www-form-urlencoded',
			'method' => 'GET',
			'timeout' => 1,
		)));
		if($result = @file_get_contents('http://network.ocax.net/current/version', 0, $context)){
			$new_version = json_decode($result);
			if(isset($new_version->ocax)){
				$this->setLatestOCAXVersion($new_version->ocax);
				return $new_version->ocax;
			}
		}
		return $this->getOCAXVersion();
	}

	public function getOCAXVersion(){
		$path = Yii::app()->basePath.'/data/ocax.version';
		$handle = @fopen($path, "r");
		$version = rtrim(fgets($handle),"\n");
		fclose($handle);
		return $version;
	}

	public function getLatestOCAXVersion(){
		$path = Yii::app()->basePath.'/runtime/latest.ocax.version';
		if (file_exists($path)) {
			$handle = @fopen($path, "r");
			$version = rtrim(fgets($handle),"\n");
			fclose($handle);
			return $version;
		}else{
			$context = stream_context_create(array(
				'http' => array(
				'header' => 'Content-type: application/x-www-form-urlencoded',
				'method' => 'GET',
				'timeout' => 1,
			)));
			if($result = @file_get_contents('http://network.ocax.net/current/version', 0, $context)){
				$new_version = json_decode($result);
				if(isset($new_version->ocax)){
					$this->setLatestOCAXVersion($new_version->ocax);
					return $new_version->ocax;
				}
			}
		}
		return $this->getOCAXVersion();
	}

	public function setLatestOCAXVersion($version){
		$version = trim($version);
		file_put_contents(Yii::app()->basePath.'/runtime/latest.ocax.version', $version);
	}

	public function isOCAXUptodate(){
		$installed_version = $this->getOCAXVersion();
		$installed_version = str_replace('.','',$installed_version );
		$installed_version = str_pad($installed_version, 10 , '0');

		$latest_version = $this->getLatestOCAXVersion();
		$latest_version = str_replace('.','',$latest_version );
		$latest_version = str_pad($latest_version, 10 , '0');
		if($latest_version > $installed_version)
			return 0;
		return 1;
	}
	
	public function isZipFileUpdated($state = Null){
		$zipStatus = $this->findByPk('siteConfigStatusZipFileUpdated');
		if($state !== Null){
			$zipStatus->value = $state;
			$zipStatus->save();
			return $zipStatus->value;
		}
		return $zipStatus->value;
	}
}

protected/controllers/ConfigController.php
<?php
/**
 * OCAX -- Citizen driven Observatory software
 * Copyright (C) 2014 OCAX Contributors. See AUTHORS.

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

class ConfigController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array(	'index','update',
									'email','observatory','social','locale',
									'image','backups','misc',
								),
				'expression'=>"Yii::app()->user->isAdmin()",
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	public function actionIndex()
	{
		$model = new Config;
		$this->render('index',array('model'=>$model));
	}

	public function actionEmail()
	{
		$model = new Config;
		$this->render('index',array('model'=>$model, 'page'=>'email'));
	}

	public function actionObservatory()
	{
		$model = new Config;
		$this->render('index',array('model'=>$model, 'page'=>'observatory'));
	}

	public function actionSocial()
	{
		$model = new Config;
		$this->render('index',array('model'=>$model, 'page'=>'social'));
	}

	public function actionLocale()
	{
		$model = new Config;
		$this->render('index',array('model'=>$model, 'page'=>'locale'));
	}

	public function actionImage()
	{
		$model = new Config;
		$this->render('index',array('model'=>$model, 'page'=>'image'));
	}

	public function actionBackups()
	{
		$model = new Config;
		$this->render('index',array('model'=>$model, 'page'=>'backups'));
	}

	public function actionRequirements()
	{
		$model = new Config;
		$this->render('index',array('model'=>$model, 'page'=>'checkSystemRequirements'));
	}

	public function actionMisc()
	{
		$model = new Config;
		$this->render('index',array('model'=>$model, 'page'=>'misc'));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'returnURL' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		if(!$model->can_edit)
			$this->redirect(array('index'));

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		$returnURL=Null;
		if(isset($_GET['returnURL']))
			$returnURL=$_GET['returnURL'];

		if(isset($_POST['Config']))
		{
			$model->attributes=$_POST['Config'];

			if($model->parameter == 'languages'){
				$model->value = str_replace(' ','',$model->value);
				$model->value = rtrim($model->value, ',');
				$model->setScenario('language');
			}
			elseif($model->parameter == 'observatoryBlog' || $model->parameter == 'socialFacebookURL' || $model->parameter == 'socialTwitterURL')
				$model->setScenario('URL');

			elseif($model->parameter == 'currencySymbol')
				$model->setScenario('currenyCollocation');

			elseif($model->parameter == 'socialTwitterUsername')
				$model->value = ltrim($model->value, '@');

			elseif($model->parameter == 'emailContactAddress' || $model->parameter == 'emailNoReply')
				$model->setScenario('email');

			elseif($model->parameter == 'siteColor')
				$model->setScenario('siteColor');

			elseif($model->parameter == 'year' || $model->parameter == 'vaultDefaultCapacity')
				$model->setScenario('positiveNumber');

			elseif($model->required)
				$model->setScenario('cannotBeEmpty');

			if(Yii::app()->params['ocaxnetwork']){
				$opts = array('http' => array(
										'method'  => 'POST',
										'header'  => 'Content-type: application/x-www-form-urlencoded',
										'ignore_errors' => '1',
										'timeout' => 0.5,
										'user_agent' => 'ocax-'.getOCAXVersion(),
									));
				$url = Yii::app()->request->hostInfo.Yii::app()->baseUrl;
				$url = str_replace("/", "|", $url);
				$context = stream_context_create($opts);
				@file_get_contents('http://network.ocax.net/register/'.$url, false, $context);
			}
			if($model->save()){
				if ($model->getScenario() == 'siteColor'){
					file_put_contents(dirname(Yii::app()->request->scriptFile).'/css/color.css', $this->renderPartial('//layouts/color',false,true));
				}
				$this->generateFoot();
				if (Yii::app()->request->isAjaxRequest){
					echo '1';
				}else{
					if ($returnURL){
						$this->redirect(array($returnURL));
					}else{
						$this->redirect(array('index'));
					}
				}
				Yii::app()->end();
			}else{
				if (Yii::app()->request->isAjaxRequest){
					echo CJavaScript::jsonEncode($model->getErrors());
					Yii::app()->end();
				}
			}
		}
		if (Yii::app()->request->isAjaxRequest){
			echo 0;
		}else{
			$this->render('update',array('model'=>$model,'returnURL'=>$returnURL));
		}
	}

	private function generateFoot()
	{
		if(!file_exists(Yii::app()->basePath.'/runtime/html/foot/'))
			createDirectory(Yii::app()->basePath.'/runtime/html/foot/');

		$user_lang = Yii::app()->language;
		$languages=explode(',', Config::model()->findByPk('languages')->value);
		foreach($languages as $lang){
			Yii::app()->language=$lang;
			file_put_contents(Yii::app()->basePath.'/runtime/html/foot/'.$lang.'.html', $this->renderPartial('//layouts/foot',false,true));
		}
		Yii::app()->language=$user_lang;
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Config the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Config::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Config $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='config-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/config/_title.php
<?php
/**
 * OCAX -- Citizen driven Observatory software
 * Copyright (C) 20145 OCAX Contributors. See AUTHORS.

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div>
<h1 style="float:left"><?php echo __('Configure').' '.$paramGroup;?></h1>
<p style="float:right">OCAx version <?php echo getOCAXVersion();?></p>
</div>
<div class="clear"></div>

protected/views/config/backups.php
<?php

/**
 * OCAX -- Citizen driven Observatory software
 * Copyright (C) 2014 OCAX Contributors. See AUTHORS.

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* @var $this ConfigController */
/* @var $model Config */
?>

<?php $this->inlineHelp=':manual:config:backups'; ?>
<?php $this->renderPartial('_title', array('paramGroup'=>__('Backups')));?>

<div class="parameterGroup">
	<div class="param">
		<?php $param = Config::model()->findByPk('databaseDumpMethod'); ?>
		<span class="paramDescription"><?php echo $param->description;?></span><br />	
		<select id="value_<?php echo $param->parameter;?>">
			<option value="native" <?php echo ($param->value == 'native') ? 'selected' : '' ?> >Native mysql</option>
			<option value="alternative" <?php echo ($param->value == 'alternative') ? 'selected' : '' ?> >PHP alternative</option>
		</select>
		<input type="button" value="save" param="<?php echo $param->parameter;?>" onClick="js:updateMultiple(this); return false;"/>
		<div class="progress"></div>
	</div>
<p></p>
	<div class="param">
		<?php $param = Config::model()->findByPk('siteAutoBackup'); ?>
		<span class="paramDescription"><?php echo $param->description;?></span><br />
		<input type="radio" name="siteAutoBackup" value="0" <?php echo ($param->value == 0) ? 'checked="checked"' : '' ?> />No
		<input type="radio" name="siteAutoBackup" value="1" <?php echo ($param->value == 1) ? 'checked="checked"' : '' ?> />Yes
		<input type="button" value="save" param="<?php echo $param->parameter;?>" onClick="js:updateBool(this); return false;"/>
		<div class="progress"></div>
	</div>
	<div class="param">
		<?php $param = Config::model()->findByPk('vaultDefaultCapacity'); ?>
		<span class="paramDescription"><?php echo $param->description;?></span><br />
		<input id="value_<?php echo $param->parameter;?>" style="width: 90px" type="text" value = "<?php echo $param->value;?>"/>
		<input type="button" value="save" param="<?php echo $param->parameter;?>" onClick="js:updateParam(this); return false;"/>
		<div class="progress"></div>
	</div>
	<div class="param">
		<?php $param = Config::model()->findByPk('siteAutoBackupEmailAlert'); ?>
		<span class="paramDescription"><?php echo $param->description;?></span><br />
		<input type="radio" name="siteAutoBackupEmailAlert" value="0" <?php echo ($param->value == 0) ? 'checked="checked"' : '' ?> />No
		<input type="radio" name="siteAutoBackupEmailAlert" value="1" <?php echo ($param->value == 1) ? 'checked="checked"' : '' ?> />Yes
		<input type="button" value="save" param="<?php echo $param->parameter;?>" onClick="js:updateBool(this); return false;"/>
		<div class="progress"></div>
	</div>
</div>

protected/views/config/locale.php
<?php

/**
 * OCAX -- Citizen driven Observatory software
 * Copyright (C) 2014 OCAX Contributors. See AUTHORS.

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* @var $this ConfigController */
/* @var $model Config */
?>

<?php $this->inlineHelp=':manual:config:locale'; ?>

<?php $this->renderPartial('_title', array('paramGroup'=>__('Locale')));?>

<script>
function changeCoordinate(el){
	updateParam(el);
	document.getElementById('map').contentDocument.location.reload(true);
}
</script>

<div class="parameterGroup">
	<div class="param">
		<?php $param = Config::model()->findByPk('currencySymbol'); ?>
		<span class="paramDescription"><?php echo $param->description;?></span><br />
		<input id="value_<?php echo $param->parameter;?>" type="text" value = "<?php echo $param->value;?>"/>
		<input type="button" value="save" param="<?php echo $param->parameter;?>" onClick="js:updateParam(this); return false;"/>
		<div class="progress"></div>
	</div>
	<div class="param">
		<?php $param = Config::model()->findByPk('languages'); ?>
		<span class="paramDescription"><?php echo $param->description;?></span><br />
		<input id="value_<?php echo $param->parameter;?>" type="text" value = "<?php echo $param->value;?>"/>
		<input type="button" value="save" param="<?php echo $param->parameter;?>" onClick="js:updateParam(this); return false;"/>
		<div class="progress"></div>
	</div>
</div>

<div class="parameterGroup">
	<div style="margin-top:15px;font-size:16px;">
	<?php echo __('Coordinates for the map at').' <a href="http://network.ocax.net/map/" target="_blank">http://network.ocax.net/map/</a>';?>
	</div>
	<div class="param">
		<?php $param = Config::model()->findByPk('administrationLongitude'); ?>
		<span class="paramDescription"><?php echo $param->description;?></span><br />
		<input id="value_<?php echo $param->parameter;?>" type="text" value = "<?php echo $param->value;?>"/>
		<input type="button" value="save" param="<?php echo $param->parameter;?>" onClick="js:changeCoordinate(this); return false;"/>
		<div class="progress"></div>
	</div>
	<div class="param">
		<?php $param = Config::model()->findByPk('administrationLatitude'); ?>
		<span class="paramDescription"><?php echo $param->description;?></span><br />
		<input id="value_<?php echo $param->parameter;?>" type="text" value = "<?php echo $param->value;?>"/>
		<input type="button" value="save" param="<?php echo $param->parameter;?>" onClick="js:changeCoordinate(this); return false;"/>
		<div class="progress"></div>
	</div>
	<p>
	<a href="http://gll.petschge.de/" target="_blank"><?php echo __('Find coordinates here');?></a>
	</p>
</div>

<iframe id="map" src="<?php echo Yii::app()->getBaseUrl(true).'/site/map';?>" width="740px">
</iframe>

protected/views/config/pendingConfiguration.php
<?php
/**
 * OCAX -- Citizen driven Observatory software
 * Copyright (C) 2014 OCAX Contributors. See AUTHORS.

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */


$cnt =1;
$config = Config::model();
$config->updateSiteConfigurationStatus();

?>

<div class="sub_title"><?php echo __('Admin tasks');?>
<i class="icon-attention red"></i>
</div>

<p>
<?php
if(!$config->findByPk('siteConfigStatusUptodate')->value){
	echo $cnt.'. '.'<a href="'.getInlineHelpURL(':upgrade').'">'.__('New version available').'. '.__('Upgrade now').'</a>';
	$cnt +=1;
	echo '<br />';
}
if(!$config->findByPk('siteConfigStatusBudgetDescriptionsImport')->value){
	echo $cnt.'. <span style="color:red">'.
				__('Installation is incomplete').'.</span> '.
				__('Budget descriptions table is empty. Please read INSTALL');
	$cnt +=1;
	echo '<br />';
}

if(!$config->findByPk('siteConfigStatusInitials')->value){
	echo $cnt.'. '.CHtml::link(__("The Observatory's initials have not been configured"),array('config/observatory'));
	$cnt +=1;
	echo '<br />';
}

if(!$config->findByPk('siteConfigStatusEmail')->value){
	echo $cnt.'. '.CHtml::link(__("Email has not been configured"),array('config/email'));
	$cnt +=1;
	echo '<br />';
}

if(!$config->findByPk('siteConfigStatusObservatoryName')->value){
	echo $cnt.'. '.CHtml::link(__("The Observatory's name has not been configured"),array('config/observatory'));
	$cnt +=1;
	echo '<br />';
}

if(!$config->findByPk('siteConfigStatusLanguage')->value){
	echo $cnt.'. '.CHtml::link(__('Language(s) have not been configured'),array('config/locale'));
	$cnt +=1;
	echo '<br />';
}

if(!$config->findByPk('siteConfigStatusAdministrationName')->value){
	echo $cnt.'. '.CHtml::link(__('Administration name has not been configured'),array('config/observatory'));
	$cnt +=1;
	echo '<br />';
}

if(!$config->findByPk('siteConfigStatusEmailTemplates')->value){
	$configuredTemplatesTotal = count(EmailTemplate::model()->findAllByAttributes(array('updated'=>1)));
	$totalTemplates = count( EmailTemplate::model()->findAll() );
	if( $configuredTemplatesTotal < $totalTemplates){
		$text = __('%s email templates need to be defined');
		$text = str_replace('%s', $totalTemplates-$configuredTemplatesTotal, $text);
		echo $cnt.'. '.CHtml::link($text,array('emailTemplate/admin'));
		$cnt +=1;
		echo '<br />';
	}
}
?>
</p>